export {default as bg_home } from "../images/bg_home.png"
export {default as mageseeker_preorder_riothome_logo} from "../images/mageseeker-preorder-riothome-logo.png"
export { default as explore_hero_bg} from "../images/explore-hero-bg.jpg"
export {default as lolkv_2023} from "../images/lolkv-2023.png"
export {default as lorka_2023} from "../images/lorka-2023.png"
export {default as tft_2023} from "../images/tft-2023.png"
export {default as val_6_2} from "../images/val-6-2.png"
export {default as wrka_2023} from "../images/wrka-2023.png"